# Generated by Django 4.1.2 on 2023-01-14 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_advert', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inkranya',
            new_name='Inkoranya',
        ),
    ]
