# Generated by Django 4.1.2 on 2023-01-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_advert', '0003_alter_inkoranya_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inkoranya',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
