# Generated by Django 4.1.2 on 2023-01-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_advert', '0004_alter_inkoranya_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imbyino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cover', models.ImageField(upload_to='imbyino/covers')),
                ('description', models.FileField(upload_to='ubukwe/descriptions')),
            ],
        ),
    ]
