# Generated by Django 4.1.2 on 2023-01-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_advert', '0005_imbyino'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ibikoresho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='ibikoresho/images')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
