# Generated by Django 4.1.2 on 2023-01-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_advert', '0006_ibikoresho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubuhinzi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.FileField(upload_to='ubuhinzi/descriptions')),
            ],
        ),
    ]
