# Generated by Django 4.1.2 on 2023-01-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_advert', '0009_amasano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ikibonezamvugo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cover', models.ImageField(upload_to='ikibonezamvugo/covers')),
                ('description', models.FileField(upload_to='ikibonezamvugo/descriptions')),
            ],
        ),
    ]
