# Generated by Django 4.1.2 on 2023-01-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_advert', '0011_umurage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hugura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='hugura/covers')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
