# Generated by Django 4.1.2 on 2023-01-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_advert', '0012_hugura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hugura',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='hugura/covers'),
        ),
        migrations.AlterField(
            model_name='ibikoresho',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ibikoresho/images'),
        ),
        migrations.AlterField(
            model_name='ikibonezamvugo',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='ikibonezamvugo/covers'),
        ),
        migrations.AlterField(
            model_name='imbyino',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='imbyino/covers'),
        ),
    ]
